# code adapted from https://github.com/mrlibw/ManiGAN
CONFIG_NAME: 'ManiGAN'

DATASET_NAME: 'textcaps'
DATA_DIR: '../data/textcaps'
GPU_ID: '1'
WORKERS: 4


TREE:
    BRANCH_NUM: 3

TRAIN:
    FLAG: True
    NET_G: '../models/textcaps_Main.pth'

    NET_C: ''
    NET_D: ''
    B_NET_D: True
    BATCH_SIZE: 16
    MAX_EPOCH: 600
    SNAPSHOT_INTERVAL: 5
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    #
    NET_E: '../DAMSMencoders/textcaps/text_encoder.pth'
    SMOOTH:
        GAMMA1: 4.0  
        GAMMA2: 5.0
        GAMMA3: 10.0  
        LAMBDA: 5.0


GAN:
    DF_DIM: 96
    GF_DIM: 48
    Z_DIM: 100
    R_NUM: 3

TEXT:
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 5
    WORDS_NUM: 25
